============================= test session starts ==============================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/tester/python/zjazd2/unit_test, inifile:
collected 4 items

test.py .F..                                                             [100%]

=================================== FAILURES ===================================
________________________ TestCalculator.test_dzielenie _________________________

self = <test.TestCalculator testMethod=test_dzielenie>

    def test_dzielenie(self):
            r = calculate(1,2,'/')
>           self.assertEqual(r,0.5)
E           AssertionError: 0 != 0.5

test.py:16: AssertionError
====================== 1 failed, 3 passed in 0.03 seconds ======================
